# docker-compose.yml - Personal AI Agent Stack

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: aiagent-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aiagent}
      POSTGRES_USER: ${POSTGRES_USER:-aiagent}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aiagent123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-aiagent}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aiagent-network
    restart: unless-stopped

  # Ollama for local AI models
  ollama:
    image: ollama/ollama:latest
    container_name: aiagent-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=30m  # Keep model loaded for 30 minutes instead of default 5m
      - OLLAMA_NUM_PARALLEL=4  # Allow up to 4 parallel requests
      - OLLAMA_MAX_LOADED_MODELS=1  # Only keep one model in memory
      - OLLAMA_FLASH_ATTENTION=true  # Enable optimized attention (if supported)
    networks:
      - aiagent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aiagent-backend
    environment:
      - TZ=${TZ:-UTC}  # Use host timezone or UTC as fallback
      - DATABASE_URL=postgresql://${POSTGRES_USER:-aiagent}:${POSTGRES_PASSWORD:-aiagent123}@postgres:5432/${POSTGRES_DB:-aiagent}
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2:latest}
      - MODEL_PROVIDER=${MODEL_PROVIDER:-ollama}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-this}
      - ENABLE_LEARNING=${ENABLE_LEARNING:-true}
      - MAX_CONVERSATION_HISTORY=${MAX_CONVERSATION_HISTORY:-1000}
      - LEARNING_UPDATE_INTERVAL=${LEARNING_UPDATE_INTERVAL:-10}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro  # Mount host timezone
    networks:
      - aiagent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    container_name: aiagent-frontend
    ports:
      - "3000:3000"
    environment:
      - TZ=${TZ:-UTC}  # Use host timezone
      - REACT_APP_API_URL=http://localhost:8000  # Changed back to localhost for browser access
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro  # Mount host timezone
    networks:
      - aiagent-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  ollama_data:
    driver: local

networks:
  aiagent-network:
    driver: bridge